feat: add linter workflow for github actions
UserOfficeProject/user-office-factory pull request #109
Opened 2022-05-09 15:07 UTC by RussellMcLean

## Description

## Motivation and Context

## How Has This Been Tested

## Fixes

## Changes

## Depends on

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

2022-05-16 07:45 UTC, TickleThePanda requested changes
I don't think this can be merged in without:
 - Fixing the YML files mentioned
 - Fixing the JSON file mentioned
 - Ignoring `templates/css/bootstrap.min.css`

2022-05-17 08:21 UTC, RussellMcLean commented
.github/workflows/* -> ignored
templates/css/bootstrap.min.css -> ignored
src/__tests__/fixtures/pdf_payloads.json -> formatting

2022-05-19 10:22 UTC, ACLay requested changes

2022-05-20 07:55 UTC, TickleThePanda approved these changes

2022-05-20 09:23 UTC, RussellMcLean commented on .github/workflows/lint.yml
> +# events but only for the develop branch
I've removed these comments altogether as they were deemed unnecessary

2022-05-24 14:47 UTC, merged