fix: Swap-2552, Printing in acrobate reader
UserOfficeProject/user-office-factory pull request #110
Opened 2022-05-11 13:35 UTC by bolmsten

## Description

Removed annotation links in the index file and cleaned up unused files

## Motivation and Context

Fix printing in acrobate reader

## How Has This Been Tested

locally

## Fixes

Swap-2552

2022-05-12 07:32 UTC, jekabs-karklins approved these changes
✅

2022-05-12 07:48 UTC, martin-trajanovski requested changes

2022-05-12 07:48 UTC, martin-trajanovski commented on src/pdf/pdfTableOfContents/index.ts
> +  console.log(translatedOutline);
You should clean this console.log

2022-05-12 07:49 UTC, jekabs-karklins commented on src/pdf/pdfTableOfContents/index.ts
> +  console.log(translatedOutline);
> You should clean this console.log

👍🏻

2022-05-12 10:59 UTC, ACLay commented on src/pdf/pdfTableOfContents/index.ts
> +  // const howManyPages = 1;
Can this commented out code be removed too?

2022-07-21 13:56 UTC, martin-trajanovski approved these changes

2022-07-22 08:47 UTC, merged